name: Spring Boot Test

on:
  push:
    branches:
      - main
      - develop  # Adjust as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Adoptium's Temurin JDK
          java-version: '17'       # Set Java version as needed

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run clean with Maven
        run: mvn clean

      - name: Run tests with Maven
        run: mvn test
